/*
 * ServicioConsumible
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * Solicitud
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2026-06-16T18:55:13.950470463Z[GMT]")

public class Solicitud {
  @SerializedName("cantidadesIniciales")
  private List<Integer> cantidadesIniciales = null;

  @SerializedName("nombreEntidades")
  private List<String> nombreEntidades = null;

  public Solicitud cantidadesIniciales(List<Integer> cantidadesIniciales) {
    this.cantidadesIniciales = cantidadesIniciales;
    return this;
  }

  public Solicitud addCantidadesInicialesItem(Integer cantidadesInicialesItem) {
    if (this.cantidadesIniciales == null) {
      this.cantidadesIniciales = new ArrayList<Integer>();
    }
    this.cantidadesIniciales.add(cantidadesInicialesItem);
    return this;
  }

   /**
   * Get cantidadesIniciales
   * @return cantidadesIniciales
  **/
  @Schema(description = "")
  public List<Integer> getCantidadesIniciales() {
    return cantidadesIniciales;
  }

  public void setCantidadesIniciales(List<Integer> cantidadesIniciales) {
    this.cantidadesIniciales = cantidadesIniciales;
  }

  public Solicitud nombreEntidades(List<String> nombreEntidades) {
    this.nombreEntidades = nombreEntidades;
    return this;
  }

  public Solicitud addNombreEntidadesItem(String nombreEntidadesItem) {
    if (this.nombreEntidades == null) {
      this.nombreEntidades = new ArrayList<String>();
    }
    this.nombreEntidades.add(nombreEntidadesItem);
    return this;
  }

   /**
   * Get nombreEntidades
   * @return nombreEntidades
  **/
  @Schema(description = "")
  public List<String> getNombreEntidades() {
    return nombreEntidades;
  }

  public void setNombreEntidades(List<String> nombreEntidades) {
    this.nombreEntidades = nombreEntidades;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Solicitud solicitud = (Solicitud) o;
    return Objects.equals(this.cantidadesIniciales, solicitud.cantidadesIniciales) &&
        Objects.equals(this.nombreEntidades, solicitud.nombreEntidades);
  }

  @Override
  public int hashCode() {
    return Objects.hash(cantidadesIniciales, nombreEntidades);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Solicitud {\n");
    
    sb.append("    cantidadesIniciales: ").append(toIndentedString(cantidadesIniciales)).append("\n");
    sb.append("    nombreEntidades: ").append(toIndentedString(nombreEntidades)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
